version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=fintech
    networks:
      - mongo-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"  # Expose Kafka on port 9092
    environment:
      - KAFKA_KRAFT_MODE=true  # Enable KRaft mode (No Zookeeper)
      - KAFKA_ADVERTISED_LISTENER=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_PORT=9092
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_INTER_BROKER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_INTER_BROKER_PORT=9092
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_PORT=9092
      - KAFKA_LISTENER_INTERNAL=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_EXTERNAL=PLAINTEXT://localhost:9092
      - KAFKA_KRAFT_MODE=true  # Run Kafka in KRaft mode (no Zookeeper needed)
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
    networks:
      - mongo-network
    restart: unless-stopped

networks:
  mongo-network:
    driver: bridge
